
server:
  port: 8182

#指定注册中心路径
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
#声明服务名称
spring:
  application:
    name: order-service


#设置feign调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        #超时时间
        readTimeout: 2000